"""Capa de aplicación hexagonal de Cadenza (ADR-0009)."""

from .exceptions import (
    ApplicationError,
    ArtifactNotFound,
    DuplicateUsername,
    Forbidden,
    InvalidEdit,
    NotAuthenticated,
    SequenceConflict,
    SessionNotFound,
    UserNotFound,
    WeakPassword,
)
from .ports import (
    ArtifactStore,
    EditEventRepository,
    InMemoryArtifactStore,
    InMemoryPasswordHasher,
    InMemoryTokenService,
    InMemoryUserRepository,
    PasswordHasher,
    PersistedFinding,
    SessionData,
    SessionRepository,
    TokenPayload,
    TokenService,
    UserRepository,
    compute_sha256,
)
from .use_cases import (
    SessionDetail,
    TranscribeResult,
    append_edit,
    authenticate,
    change_password,
    create_user,
    get_session,
    list_findings,
    list_users,
    transcribe_score,
    update_user,
)
from .user import Role, User

__all__ = [
    "ApplicationError",
    "ArtifactNotFound",
    "ArtifactStore",
    "DuplicateUsername",
    "EditEventRepository",
    "Forbidden",
    "InMemoryArtifactStore",
    "InMemoryPasswordHasher",
    "InMemoryTokenService",
    "InMemoryUserRepository",
    "InvalidEdit",
    "NotAuthenticated",
    "PasswordHasher",
    "PersistedFinding",
    "Role",
    "SequenceConflict",
    "SessionData",
    "SessionDetail",
    "SessionNotFound",
    "SessionRepository",
    "TokenPayload",
    "TokenService",
    "TranscribeResult",
    "User",
    "UserNotFound",
    "UserRepository",
    "WeakPassword",
    "append_edit",
    "authenticate",
    "change_password",
    "compute_sha256",
    "create_user",
    "get_session",
    "list_findings",
    "list_users",
    "transcribe_score",
    "update_user",
]
